# Generated by Django 2.2.1 on 2019-06-02 16:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_client', models.BooleanField(default=False)),
                ('is_contractor', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address_1', models.CharField(max_length=150, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=150, verbose_name='Address (#2)')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Region')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('postal_code', models.CharField(max_length=150, verbose_name='Postal code')),
                ('po_box_no', models.IntegerField(blank=True, verbose_name='P.O. Box no')),
                ('landline_no', models.IntegerField(verbose_name='Work number')),
                ('mobile_no_1', models.IntegerField(verbose_name='Mobile number')),
                ('mobile_no_2', models.IntegerField(blank=True, verbose_name='Mobile number (#2)')),
                ('bank_name_1', models.CharField(max_length=150, verbose_name='Bank name')),
                ('bank_account_no_1', models.CharField(max_length=150, verbose_name='Bank account number')),
                ('bank_name_2', models.CharField(blank=True, max_length=150, verbose_name='Bank name (#2)')),
                ('bank_account_no_2', models.CharField(blank=True, max_length=150, verbose_name='Bank account number (#2)')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('national_id', models.IntegerField(verbose_name='National I.D.')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP Code')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisors',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address_1', models.CharField(max_length=150, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=150, verbose_name='Address (#2)')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Region')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('postal_code', models.CharField(max_length=150, verbose_name='Postal code')),
                ('po_box_no', models.IntegerField(blank=True, verbose_name='P.O. Box no')),
                ('landline_no', models.IntegerField(verbose_name='Work phone number')),
                ('mobile_no_1', models.IntegerField(verbose_name='Mobile number')),
                ('mobile_no_2', models.IntegerField(blank=True, verbose_name='Mobile number (#2)')),
                ('bank_name_1', models.CharField(max_length=150, verbose_name='Bank name')),
                ('bank_account_no_1', models.CharField(max_length=150, verbose_name='Bank account number')),
                ('bank_name_2', models.CharField(blank=True, max_length=150, verbose_name='Bank name (#2)')),
                ('bank_account_no_2', models.CharField(blank=True, max_length=150, verbose_name='Bank account number (#2)')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('national_id', models.IntegerField(verbose_name='National I.D.')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP Code')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contractor',
                'verbose_name_plural': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address_1', models.CharField(max_length=150, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=150, verbose_name='Address (#2)')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Region')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('postal_code', models.CharField(max_length=150, verbose_name='Postal code')),
                ('po_box_no', models.IntegerField(blank=True, verbose_name='P.O. Box no')),
                ('landline_no', models.IntegerField(verbose_name='Landline number')),
                ('mobile_no_1', models.IntegerField(verbose_name='Mobile number')),
                ('mobile_no_2', models.IntegerField(blank=True, verbose_name='Mobile number (#2)')),
                ('bank_name_1', models.CharField(max_length=150, verbose_name='Bank name')),
                ('bank_account_no_1', models.CharField(max_length=150, verbose_name='Bank account number')),
                ('bank_name_2', models.CharField(blank=True, max_length=150, verbose_name='Bank name (#2)')),
                ('bank_account_no_2', models.CharField(blank=True, max_length=150, verbose_name='Bank account number (#2)')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('national_id', models.IntegerField(verbose_name='National I.D.')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP Code')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
