# Generated by Django 2.2.1 on 2019-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='bank_account_no_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank account number (#2)'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='bank_name_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank name (#2)'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='mobile_no_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile number (#2)'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='po_box_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='P.O. Box no'),
        ),
    ]
