# Generated by Django 2.2.1 on 2019-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190618_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address (#2)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address (#2)'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='address_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address (#2)'),
        ),
    ]
