# Generated by Django 2.2.1 on 2019-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190618_1955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supervisor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
