# Generated by Django 2.2.1 on 2019-06-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('floors', '0001_initial'),
        ('units', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorRooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_room_name', models.CharField(choices=[('bedroom', 'bed'), ('bathroom', 'bathroom'), ('kitchen', 'kitchen'), ('dressing room', 'dressing room')], default='bedroom', max_length=150, verbose_name='Room Type')),
                ('room_desc', models.CharField(blank=True, max_length=150, verbose_name='Room Description')),
                ('room_desc_2', models.CharField(blank=True, max_length=150, verbose_name='Room Description')),
                ('room_covered_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Covered Area')),
                ('covered_area_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.CoveredAreaUnits', verbose_name='Covered Area Unit')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.ProjectFloors', verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Floor Rooms',
                'verbose_name_plural': 'Floor Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomSides',
            fields=[
                ('room_side_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_side_name', models.CharField(choices=[('floor', 'floor'), ('roof', 'roof'), ('wall 1', 'wall 1'), ('wall 2', 'wall 2'), ('wall 3', 'wall 3'), ('wall 4', 'wall 4')], default='floor', max_length=150, verbose_name='Room Side')),
                ('room_side_desc_1', models.CharField(blank=True, max_length=150, verbose_name='Room Side Description')),
                ('room_side_desc_2', models.CharField(blank=True, max_length=150, verbose_name='Room Side Description')),
                ('room_side_covered_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Side Covered Area')),
                ('room_side_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Side Length')),
                ('room_side_width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Side Width')),
                ('length_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.LengthUnits', verbose_name='Length Unit')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.FloorRooms', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Sides',
                'verbose_name_plural': 'Room Sides',
            },
        ),
        migrations.CreateModel(
            name='ProjectRoomTypes',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(choices=[('bedroom', 'bedroom'), ('bathroom', 'bathroom'), ('kitchen', 'kitchen'), ('dressing room', 'dressing room')], default='bedroom', max_length=150, verbose_name='Room Type')),
                ('room_type_desc', models.CharField(blank=True, max_length=150, verbose_name='Room Type Description')),
                ('room_type_desc_1', models.CharField(blank=True, max_length=150, verbose_name='Room Type Description')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectTypes', verbose_name='Project Type')),
            ],
            options={
                'verbose_name': 'Project Room Types',
                'verbose_name_plural': 'Project Room Types',
            },
        ),
        migrations.AddField(
            model_name='floorrooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.ProjectRoomTypes', verbose_name='Room Type'),
        ),
    ]
