# Generated by Django 2.2.1 on 2019-06-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '__first__'),
        ('units', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('project_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_type_name', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential')], default='residential', max_length=150, verbose_name='Project type')),
                ('project_type_desc', models.CharField(blank=True, max_length=150, verbose_name='Project Type Description')),
            ],
            options={
                'verbose_name': 'Project Types',
                'verbose_name_plural': 'Project Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('project_desc_1', models.CharField(max_length=150, verbose_name='Project Description')),
                ('project_desc_2', models.CharField(blank=True, max_length=150, verbose_name='Project Description')),
                ('project_desc_3', models.CharField(blank=True, max_length=150, verbose_name='Project Description')),
                ('site_address_1', models.CharField(max_length=150, verbose_name='Site Address')),
                ('site_address_2', models.CharField(blank=True, max_length=150, verbose_name='Site Address')),
                ('site_address_3', models.CharField(blank=True, max_length=150, verbose_name='Site Address')),
                ('site_postal_code', models.CharField(max_length=150, verbose_name='Site Postal Code')),
                ('site_po_box_no', models.CharField(max_length=150, verbose_name='Site P.O. Box Number')),
                ('plot_size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Plot Size')),
                ('no_of_floors', models.IntegerField(verbose_name='Number of Floors')),
                ('total_covered_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Covered Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name='City')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Region', verbose_name='Country')),
                ('covered_area_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.CoveredAreaUnits', verbose_name='Covered Area Unit')),
                ('plot_area_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.PlotAreaUnits', verbose_name='Plot Area Units')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectTypes', verbose_name='Project Type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Country', verbose_name='Region')),
            ],
        ),
    ]
