# Generated by Django 2.2.1 on 2019-06-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Contractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Supervisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
