# Generated by Django 2.2.1 on 2019-06-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('floors', '__first__'),
        ('phases', '__first__'),
        ('rooms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('expense_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type_name', models.CharField(choices=[('labour', 'labour'), ('material', 'material')], default='labour', max_length=150, verbose_name='Expense Type')),
                ('expense_type_desc', models.CharField(blank=True, max_length=150, verbose_name='Expense Type Description')),
                ('expense_type_desc_2', models.CharField(blank=True, max_length=150, verbose_name='Expense Type Description')),
            ],
            options={
                'verbose_name': 'Expense Types',
                'verbose_name_plural': 'Expense Types',
            },
        ),
        migrations.CreateModel(
            name='ProjectExpenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=150, verbose_name='Expense Name')),
                ('expense_desc', models.CharField(max_length=150, verbose_name='Expense Description')),
                ('expense_desc2', models.CharField(max_length=150, verbose_name='Expense Description')),
                ('expense_value', models.CharField(max_length=150, verbose_name='Expense Value')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phases.PhaseActivities', verbose_name='Activity')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.ExpenseTypes', verbose_name='Expense Type')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floors.ProjectFloors', verbose_name='Floor')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phases.ProjectPhases', verbose_name='Phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.FloorRooms', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Project Expenses',
                'verbose_name_plural': 'Project Expenses',
            },
        ),
    ]
