# Generated by Django 2.2.1 on 2019-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredAreaUnits',
            fields=[
                ('covered_area_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('covered_area_unit_name', models.CharField(choices=[('square feet', 'square feet'), ('square meters', 'square meters'), ('square yards', 'square yards')], default='square feet', max_length=150, verbose_name='Covered Area Unit Name')),
                ('covered_area_unit_desc', models.CharField(blank=True, max_length=150, verbose_name='Covered Area Unit Description')),
            ],
            options={
                'verbose_name': 'Covered Area Units',
                'verbose_name_plural': 'Covered Area Units',
            },
        ),
        migrations.CreateModel(
            name='LengthUnits',
            fields=[
                ('length_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('length_unit_name', models.CharField(choices=[('meters', 'meters'), ('feet', 'feet'), ('yards', 'yards'), ('inches', 'inches'), ('millimeters', 'millimeters'), ('centimeters', 'centimeters')], default='meters', max_length=150, verbose_name='Length Unit')),
                ('length_unit_desc', models.CharField(blank=True, max_length=150, verbose_name='Length Unit Description')),
            ],
            options={
                'verbose_name': 'Length Units',
                'verbose_name_plural': 'Length Units',
            },
        ),
        migrations.CreateModel(
            name='PlotAreaUnits',
            fields=[
                ('plot_area_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_area_unit_name', models.CharField(choices=[('square feet', 'square feet'), ('square meters', 'square meters'), ('square yards', 'square yards'), ('marla', 'marla'), ('kanal', 'kanal')], default='square feet', max_length=150, verbose_name='Plot Area Units')),
                ('plot_area_unit_desc', models.CharField(blank=True, max_length=150, verbose_name='Plot Area Unit Description')),
            ],
            options={
                'verbose_name': 'Plot Area Units',
                'verbose_name_plural': 'Plot Area Units',
            },
        ),
    ]
