# Generated by Django 2.2.1 on 2019-06-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '__first__'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFloors',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(choices=[('basement', 'basement'), ('ground', 'ground'), ('first', 'first floor'), ('second', 'second floor')], default='ground', max_length=150, verbose_name='Floor Level')),
                ('floor_desc', models.CharField(blank=True, max_length=150, verbose_name='Floor Description')),
                ('floor_covered_area', models.IntegerField(verbose_name='Floor Covered Area')),
                ('covered_area_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.CoveredAreaUnits', verbose_name='Covered Area Unit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Floors',
                'verbose_name_plural': 'Project Floors',
            },
        ),
    ]
